import type { AuctionPlayer, AuctionTeam, InitialAuctionState } from "./auction-types";

export const mockAuctionPlayers: AuctionPlayer[] = [
  {
    id: "virat-kohli",
    name: "Virat Kohli",
    role: "Batter",
    basePriceLakhs: 200,
    origin: "India",
    image: "/player-silhouette.svg",
    accentFrom: "#f59e0b",
    accentTo: "#fb7185",
  },
  {
    id: "jasprit-bumrah",
    name: "Jasprit Bumrah",
    role: "Bowler",
    basePriceLakhs: 150,
    origin: "India",
    image: "/player-silhouette.svg",
    accentFrom: "#22d3ee",
    accentTo: "#60a5fa",
  },
  {
    id: "hardik-pandya",
    name: "Hardik Pandya",
    role: "All-Rounder",
    basePriceLakhs: 180,
    origin: "India",
    image: "/player-silhouette.svg",
    accentFrom: "#fb7185",
    accentTo: "#a78bfa",
  },
  {
    id: "ruturaj-gaikwad",
    name: "Ruturaj Gaikwad",
    role: "Batter",
    basePriceLakhs: 120,
    origin: "India",
    image: "/player-silhouette.svg",
    accentFrom: "#facc15",
    accentTo: "#f97316",
  },
  {
    id: "kl-rahul",
    name: "KL Rahul",
    role: "Wicketkeeper",
    basePriceLakhs: 140,
    origin: "India",
    image: "/player-silhouette.svg",
    accentFrom: "#38bdf8",
    accentTo: "#2dd4bf",
  },
  {
    id: "rashid-khan",
    name: "Rashid Khan",
    role: "Bowler",
    basePriceLakhs: 170,
    origin: "Afghanistan",
    image: "/player-silhouette.svg",
    accentFrom: "#34d399",
    accentTo: "#22d3ee",
  },
];

export const mockAuctionTeams: AuctionTeam[] = [
  {
    id: "mumbai-mavericks",
    name: "Mumbai Mavericks",
    shortCode: "MM",
    purseLakhs: 9000,
    primaryColor: "#2563eb",
    secondaryColor: "#22d3ee",
  },
  {
    id: "chennai-kings",
    name: "Chennai Kings",
    shortCode: "CK",
    purseLakhs: 8750,
    primaryColor: "#f59e0b",
    secondaryColor: "#facc15",
  },
  {
    id: "delhi-strikers",
    name: "Delhi Strikers",
    shortCode: "DS",
    purseLakhs: 8600,
    primaryColor: "#3b82f6",
    secondaryColor: "#93c5fd",
  },
  {
    id: "bengal-tigers",
    name: "Bengal Tigers",
    shortCode: "BT",
    purseLakhs: 8420,
    primaryColor: "#f97316",
    secondaryColor: "#ef4444",
  },
  {
    id: "hyderabad-fire",
    name: "Hyderabad Fire",
    shortCode: "HF",
    purseLakhs: 8880,
    primaryColor: "#fb7185",
    secondaryColor: "#f59e0b",
  },
];

export const initialAuctionState: InitialAuctionState = {
  currentPlayerId: mockAuctionPlayers[0].id,
  currentBidLakhs: mockAuctionPlayers[0].basePriceLakhs,
  highestBidderId: null,
  bidIncrementLakhs: 10,
  countdownSeconds: 15,
  bidHistory: [
    {
      id: 1,
      type: "nomination",
      playerId: mockAuctionPlayers[0].id,
      playerName: mockAuctionPlayers[0].name,
      label: `Lot 01 opened for ${mockAuctionPlayers[0].name}`,
    },
  ],
};
