export const seedPlayers = [
  {
    slug: "virat-kohli",
    name: "Virat Kohli",
    role: "BATTER",
    country: "India",
    basePrice: 200,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#d7b46a",
    accentTo: "#f97316",
  },
  {
    slug: "jasprit-bumrah",
    name: "Jasprit Bumrah",
    role: "BOWLER",
    country: "India",
    basePrice: 180,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#38bdf8",
    accentTo: "#2563eb",
  },
  {
    slug: "hardik-pandya",
    name: "Hardik Pandya",
    role: "ALL_ROUNDER",
    country: "India",
    basePrice: 190,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#fb7185",
    accentTo: "#f97316",
  },
  {
    slug: "ruturaj-gaikwad",
    name: "Ruturaj Gaikwad",
    role: "BATTER",
    country: "India",
    basePrice: 125,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#facc15",
    accentTo: "#f59e0b",
  },
  {
    slug: "kl-rahul",
    name: "KL Rahul",
    role: "WICKETKEEPER",
    country: "India",
    basePrice: 150,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#22c55e",
    accentTo: "#14b8a6",
  },
  {
    slug: "rashid-khan",
    name: "Rashid Khan",
    role: "BOWLER",
    country: "Afghanistan",
    basePrice: 170,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#34d399",
    accentTo: "#06b6d4",
  },
  {
    slug: "suryakumar-yadav",
    name: "Suryakumar Yadav",
    role: "BATTER",
    country: "India",
    basePrice: 165,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#60a5fa",
    accentTo: "#2563eb",
  },
  {
    slug: "ravindra-jadeja",
    name: "Ravindra Jadeja",
    role: "ALL_ROUNDER",
    country: "India",
    basePrice: 175,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#22c55e",
    accentTo: "#84cc16",
  },
  {
    slug: "shubman-gill",
    name: "Shubman Gill",
    role: "BATTER",
    country: "India",
    basePrice: 160,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#f59e0b",
    accentTo: "#f97316",
  },
  {
    slug: "arshdeep-singh",
    name: "Arshdeep Singh",
    role: "BOWLER",
    country: "India",
    basePrice: 110,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#0ea5e9",
    accentTo: "#22d3ee",
  },
  {
    slug: "sanju-samson",
    name: "Sanju Samson",
    role: "WICKETKEEPER",
    country: "India",
    basePrice: 145,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#ef4444",
    accentTo: "#f97316",
  },
  {
    slug: "mitchell-starc",
    name: "Mitchell Starc",
    role: "BOWLER",
    country: "Australia",
    basePrice: 185,
    imageUrl: "/player-silhouette.svg",
    accentFrom: "#eab308",
    accentTo: "#f97316",
  },
] as const;

export const seedTeams = [
  {
    code: "MM",
    name: "Mumbai Mavericks",
    purse: 9000,
    color: "#2563eb",
    secondaryColor: "#22d3ee",
  },
  {
    code: "CK",
    name: "Chennai Kings",
    purse: 8750,
    color: "#f59e0b",
    secondaryColor: "#facc15",
  },
  {
    code: "DS",
    name: "Delhi Strikers",
    purse: 8600,
    color: "#3b82f6",
    secondaryColor: "#93c5fd",
  },
  {
    code: "BT",
    name: "Bengal Tigers",
    purse: 8420,
    color: "#f97316",
    secondaryColor: "#ef4444",
  },
  {
    code: "HF",
    name: "Hyderabad Fire",
    purse: 8880,
    color: "#fb7185",
    secondaryColor: "#f59e0b",
  },
  {
    code: "RC",
    name: "Royal Chargers",
    purse: 8540,
    color: "#a855f7",
    secondaryColor: "#ec4899",
  },
] as const;
